spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social-app?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: misho.27091968

  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true

    #JPA Settings
  jpa:
    hibernate.ddl_auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
